### ISSUE TITLE
'All works' button on the graphic medicine concept page finds no results

### ISSUE THREAD

**Issue by pollecuttn** [wellcomecollection/catalogue-api#780]
Reported in [Slack](https://wellcome.slack.com/archives/C8X9YKM5X/p1715185209367879):

> If I'm in a concept: https://wellcomecollection.org/concepts/jzyrfxa5 then click to see all 90 works I get: https://wellcomecollection.org/search/works?genres.label=%22graphic+medicine%22 (which says there are no works)

I think this might only be affecting the 'graphic medicine' concept as other concepts work as expected:
[lithographs](https://wellcomecollection.org/search/works?genres.label=%22Lithographs%22) from https://wellcomecollection.org/concepts/fmydsuw2
[paintings](https://wellcomecollection.org/search/works?genres.label=%22Paintings%22) from https://wellcomecollection.org/concepts/q9b2ep5v
[parodies](https://wellcomecollection.org/concepts/g3sa5kv4) from https://wellcomecollection.org/concepts/g3sa5kv4

Changing 'graphic' to 'Graphic' in the link from the concept page works - you get the relevant 90 works: [https://wellcomecollection.org/search/works?genres.label=%22Graphic+medicine%2](https://wellcomecollection.org/search/works?genres.label=%22Graphic+medicine%22).

I've looked at Sierra and all those 90 records use 'Graphic' not 'graphic' in their 655s.

'graphic medicine' isn't in the type/technique dropdown when you [search with no search term](https://wellcomecollection.org/search/works). Not sure if this is a red herring or not.

## To do
- [ ] get the 'All works' button link on the concepts page https://wellcomecollection.org/concepts/jzyrfxa5 working
- [ ] can we check if the same is happening on other concepts?

**Comment by paul-butcher** [comment]
I suspect this is due to a change in case normalisation for label-derived identifiers.  If the term was present before that change, it would bear the same case as the label.  I'll try to find that change. there were odd discrepancies - e.g. where multi-word terms were sometimes title case and sometimes sentence case.

**Comment by paul-butcher** [comment]
I suspect the solution is to make the link case-insensitive by making the query search in the lowercase_keyword subfield, rather than keyword.

**Comment by paul-butcher** [comment]
The correct, end-goal fix to this is to make it all work with identifiers.  But that is a massive change

**Comment by paul-butcher** [comment]
Actually.  I think the only case normalisation we do is for comparison, rather than storage.  I suspect that when this term was first encountered, it was `graphic medicine`, then someone fixed it to be `Graphic medicine`, but because we have it stored as `graphic medicine` it's not being overwritten with the correct capitalisation.

**Comment by paul-butcher** [comment]
[This is where the magic happens](https://github.com/wellcomecollection/concepts-pipeline/blob/ad4010730d183faabaaf2b105fec298d75cbe3fe/aggregator/src/main/scala/weco/concepts/aggregator/NotInIndexFlow.scala#L24).

For performance reasons, we only insert each Concept once.  If we find one that is already there, we discard it, rather than rely on ES's upsert behaviour.

**Comment by paul-butcher** [comment]
[Hurrah for quality commentary.](https://github.com/wellcomecollection/concepts-pipeline/blob/103075750ff587d1139aa25da2b6707051497cd9/aggregator/src/main/scala/weco/concepts/aggregator/ConceptsAggregator.scala#L67).  Thank you me-from-the-past

**Comment by paul-butcher** [comment]
This can be fixed quickly by me deleting the `graphic medicine` concept(s), then notifying the Concepts pipeline of one of the corresponding Works.  That should fix it.

I do have a fix to I can add to the concepts pipeline to make sure the most up-to-date labels are represented in Concepts, but I fear it might actually make this problem happen more often.

For example, [k949jyjy](https://wellcomecollection.org/works/k949jyjy) has both `Graphic Novels` and `graphic novels` (both of which are [av6wszv9](https://wellcomecollection.org/concepts/av6wszv9)).  Allowing the Concept's label to be updated by this document would result in it nondeterministically being one or the other.

**Comment by paul-butcher** [comment]
I think I'll fix this by messing with the record. 

With the current code, the label is stable, if it is right, then it will continue to be right.  If it is wrong, we can correct it at it will then continue to be right.

If I change the way this all works, then the labels can change willy-nilly and in unpredictable ways.

**Comment by paul-butcher** [comment]
I fancy [this](https://wellcomecollection.org/works/he9k5vu8) might be the/a culprit. It has a Subject of `graphic medicine | congresses`

**Comment by paul-butcher** [comment]
I think that may be because about only uses the whole subject, and not subject concepts
