### ISSUE TITLE
Requests API & Items API must use differing credentials

### ISSUE THREAD

**Issue by kenoir** [wellcomecollection/catalogue-api#95]
The requests service & the items service currently share the same sierra credentials. The requests service will be able to access PII and must have a different set of credentials with the appropriate access. Items can then have a reduced access profile.

**Comment by alexwlchan** [comment]
Natalie and I have been through the list of Sierra API keys.

- We removed API keys for Digirati folk who'd been working on the identity services
- We disabled an experience API key because we couldn't work out what it was being used for (starting `JD3y`). If it's not claimed by somebody it'll expire in a year.
- We removed permissions for patron data from two API keys that don't need it (James's personal key and the items API key)

Additional note for dev folks: you can use the `/info/token` endpoint on the Sierra API to see what permissions a given set of API credentials have. See https://sandbox.iii.com/iii/sierra-api/swagger/index.html#!/info/Get_token_information_get_0
